// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvokutukqxsupfifluex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2b2t1dHVrcXhzdXBmaWZsdWV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEzMTY1ODYsImV4cCI6MjA2Njg5MjU4Nn0.wMu9WfGY21G3w5-6AxkcOCaLXSFG5YwvdpPL_8nvBZI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});